name: CI

on: [push, workflow_dispatch]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Download
      run: Invoke-WebRequest https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip -OutFile ngrok.zip
    - name: Extract
      run: Expand-Archive ngrok.zip
    - name: Configure ngrok
      run: |
        echo "version: '2'" > ngrok.yml
        echo "authtoken: $Env:NGROK_AUTH_TOKEN" >> ngrok.yml
        echo "tunnels:" >> ngrok.yml
        echo "  rdp:" >> ngrok.yml
        echo "    proto: tcp" >> ngrok.yml
        echo "    addr: 3389" >> ngrok.yml
        echo "    region: ap" >> ngrok.yml
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
    - name: Enable TS
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0
    - run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
    - run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
    - run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "PelerAyam!" -Force)
    - name: Create Tunnel
      run: .\ngrok\ngrok.exe start -config ngrok.yml rdp
